In [21]:
# Example solution
import numpy as np
n=12
a = np.arange(1, n+1)
x = np.max(np.vstack((a,a[::-1])), axis=0)
np.max(np.stack(np.meshgrid(x,x),axis=2), axis=2)

array([[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12],
       [12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12],
       [12, 11, 10,  9,  9,  9,  9,  9,  9, 10, 11, 12],
       [12, 11, 10,  9,  8,  8,  8,  8,  9, 10, 11, 12],
       [12, 11, 10,  9,  8,  7,  7,  8,  9, 10, 11, 12],
       [12, 11, 10,  9,  8,  7,  7,  8,  9, 10, 11, 12],
       [12, 11, 10,  9,  8,  8,  8,  8,  9, 10, 11, 12],
       [12, 11, 10,  9,  9,  9,  9,  9,  9, 10, 11, 12],
       [12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12],
       [12, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

-----
#### Задание 14

### Федоров Сергей СКБ172

Оценка: 0.5

Комментарий: While=2

In [0]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [0]:
import numpy as np
# np.set_printoptions(precision=3) 
n = int(input())
NN = np.zeros((n,n))
if n%2 == 0:
  startN = n // 2 + 1
  iSt = n // 2
  istt = n//2 - 1
  while startN <= n:
    NN[iSt] = startN
    NN[istt] = startN
    NN[:,iSt] = startN
    NN[:,istt] = startN
    # print('ist = ', iSt,"istt = ",'Start =', startN)
    iSt +=1
    istt -=1
    startN+=1
if n % 2 == 1:
  NN[n//2] = n // 2 + 1
  startN = n // 2 + 2
  iSt = n // 2 +1
  istt = n//2 - 1
  while startN <= n:
    NN[iSt] = startN
    NN[istt] = startN
    NN[:,iSt] = startN
    NN[:,istt] = startN
    # print('ist = ', iSt,"istt = ",'Start =', startN)
    iSt +=1
    istt -=1
    startN+=1
print( NN)

11
[[11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11.]
 [11. 10.  9.  9.  9.  9.  9.  9.  9. 10. 11.]
 [11. 10.  9.  8.  8.  8.  8.  8.  9. 10. 11.]
 [11. 10.  9.  8.  7.  7.  7.  8.  9. 10. 11.]
 [11. 10.  9.  8.  7.  6.  7.  8.  9. 10. 11.]
 [11. 10.  9.  8.  7.  7.  7.  8.  9. 10. 11.]
 [11. 10.  9.  8.  8.  8.  8.  8.  9. 10. 11.]
 [11. 10.  9.  9.  9.  9.  9.  9.  9. 10. 11.]
 [11. 10. 10. 10. 10. 10. 10. 10. 10. 10. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]]


### Алексеев Кирилл СКБ172

Оценка: 0

Комментарий: While=4

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [ ]:
import numpy as np

def Volna(a, b, matr, num):
    global k
    matr[a][b] = num
    if a > 0:
        if matr[a - 1][b] > num + 1:
            matr = Volna(a - 1, b, matr, num + 1)
    if b > 0:
        if matr[a][b - 1] > num + 1:
            matr = Volna(a, b - 1, matr, num + 1)
    if a < k - 1:
        if matr[a + 1][b] > num + 1:
            matr = Volna(a + 1, b, matr, num + 1)
    if b < k - 1:
        if matr[a][b + 1] > num + 1:
            matr = Volna(a, b + 1, matr, num + 1)
    if (a > 0) and (b > 0):
        if matr[a - 1][b - 1] > num + 1:
            matr = Volna(a - 1, b - 1, matr, num + 1)
    if (a > 0) and (b < k - 1):
        if matr[a - 1][b + 1] > num + 1:
            matr = Volna(a - 1, b + 1, matr, num + 1)
    if (a < k - 1) and (b > 0):
        if matr[a + 1][b - 1] > num + 1:
            matr = Volna(a + 1, b - 1, matr, num + 1)
    if (a < k - 1) and (b < k - 1):
        if matr[a + 1][b + 1] > num + 1:
            matr = Volna(a + 1, b + 1, matr, num + 1)
    return matr
    
    
def Zap(matr):
    global k
    i = 0 
    j = 0
    while i < k:
        while j < k:
            matr[i][j] = 1000000000
            j = j + 1
        i = i + 1
    return matr

def MatrixCreation(l):
    matr = np.empty((l, l))
    matr = Zap(matr)
    if l % 2 != 0:
        p = (l // 2)
        f = int(k - p)
        matr = Volna(p, p, matr, f)
    else:
        if l >= 2:
            p = int(l / 2)
            matr = Volna(p, p, matr, k - p + 1)
            matr = Volna(p - 1, p, matr, k - p + 1)
            matr = Volna(p, p - 1, matr, k - p + 1)
            matr = Volna(p - 1, p - 1, matr, k - p + 1)
        else:
            i = 0
            j = 0
            while i < k:
                while j < k:
                    matr[i][j] = k
                    j = j + 1
                i = i + 1
    return matr
    
k = int(input())
m = MatrixCreation(k)
print(m)

### Анчугов Роман СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [ ]:
import numpy as np
n = 5
arr = np.ones((n,n))
for i in range(0, int(n / 2)):
    arr[i][i:n-i] *= n - i
    arr[n-i-1][i:n-i] *= n - i
    arr = np.rot90(arr, -1)
    
    arr[i][i + 1:n - i - 1] *= n - i
    arr[n-i-1][i+1:n-i-1] *= n - i
    arr = np.rot90(arr, 1)
    
if n % 2 != 0:
    center = int((n + 1)/2)
    arr[center - 1][center - 1] *= center
arr

### Акинина Алёна СКБ172

Оценка: 0.25

Комментарий: For=2, Recursion=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [181]:
import numpy as np
n = int(input())
arr = np.empty((n,n))
def pyramid(k,n):
    for i in range(k,n): 
        for j in range(k,n):
            arr[i][j] = n 
    if n > 1:        
        return pyramid(k+1,n-1)  
    elif n == 1:
        return arr
print(pyramid(0,n))

10
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


### Лисьев Александр СКБ171

Оценка: 0.75

Комментарий: For=1

In [14]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [15]:
import numpy as np
n=int(input())
A = np.ones((n,n))
A += n-1
for i in range(1, n//2+1):
    B = A[i:n-i, i:n-i]
    B -= 1
print(A)

10
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


### Чердак Александр СКБ171

Оценка: 0

Комментарий: No solution.

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


### Шелепова Алена СКБ172

Оценка: 1

Комментарий: Best solution!

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [16]:
import numpy as np

def func_piram(n):
    a = np.arange(1,n+1)
    b = np.maximum(a,a[::-1])
    return np.maximum.outer(b,b)

func_piram(8)

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [8, 7, 7, 7, 7, 7, 7, 8],
       [8, 7, 6, 6, 6, 6, 7, 8],
       [8, 7, 6, 5, 5, 6, 7, 8],
       [8, 7, 6, 5, 5, 6, 7, 8],
       [8, 7, 6, 6, 6, 6, 7, 8],
       [8, 7, 7, 7, 7, 7, 7, 8],
       [8, 8, 8, 8, 8, 8, 8, 8]])

### Шнейдер Алиса СКБ172

Оценка: 0.75

Комментарий: For=1

In [135]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [138]:
import numpy as np

n = int(input())
x = np.ones((n, n), dtype=int)
for i in range(n):
    x[i:n - i,i:n - i] = n - i
print(x)

 7


[[7 7 7 7 7 7 7]
 [7 6 6 6 6 6 7]
 [7 6 5 5 5 6 7]
 [7 6 5 4 5 6 7]
 [7 6 5 5 5 6 7]
 [7 6 6 6 6 6 7]
 [7 7 7 7 7 7 7]]


### Зайцева Анастасия СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [25]:
import numpy as np

n = int(input())
a = np.empty((n,n))
if n%2 == 0: m = n//2
else: m = n//2+1
for i in range(m):
    a[i:n-i,i:n-i] = n-i
print(a)

 9


[[9. 9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 8. 8. 8. 8. 8. 8. 8. 9.]
 [9. 8. 7. 7. 7. 7. 7. 8. 9.]
 [9. 8. 7. 6. 6. 6. 7. 8. 9.]
 [9. 8. 7. 6. 5. 6. 7. 8. 9.]
 [9. 8. 7. 6. 6. 6. 7. 8. 9.]
 [9. 8. 7. 7. 7. 7. 7. 8. 9.]
 [9. 8. 8. 8. 8. 8. 8. 8. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9.]]


### Полуяктов Анатолий СКБ171

Оценка: 0

Комментарий: For=4, While=5

In [7]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [8]:

# put your python code here
n = int(input())
i,j= 0, -1
max_j , max_i = n-1 ,n-1
min_j,min_i = 0 , 1
count = n+1
matrix = [[0 for j in range(n)]for i in range(n)]
while True:
    count-=1
    while j < max_j:
        j+=1
        matrix[i][j]=count
        #count+=1
    max_j-=1
    while i < max_i:
        i+=1
        matrix[i][j]=count
        #count+=1
    max_i-=1
    while j > min_j:
        j-=1
        matrix[i][j]=count
        #count+=1
    min_j+=1
    while i > min_i:
        i-=1
        matrix[i][j]=count
        #count+=1
    min_i+=1
    if j == (n-1)//2 and i == n//2:
        break
for i in range(n):
    for j in range(n):
        print(matrix[i][j], end=" ")
    print()

7
7 7 7 7 7 7 7 
7 6 6 6 6 6 7 
7 6 5 5 5 6 7 
7 6 5 4 5 6 7 
7 6 5 5 5 6 7 
7 6 6 6 6 6 7 
7 7 7 7 7 7 7 


### Фомин Андрей СКБ172

Оценка: 0

Комментарий: No solution.

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


### Марипова Жасмин СКБ171

Оценка: 0.75

Комментарий: For=1

In [0]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [0]:
import numpy as np

n = int(input())
a = np.ones((n, n), dtype = int)
for i in range(n):
    a[i:n - i,i:n - i] = n - i
a

7


array([[7, 7, 7, 7, 7, 7, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 5, 4, 5, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 7, 7, 7, 7, 7, 7]])

### Зоричев Борис СКБ172

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [22]:
import numpy as np
n=10
A=np.ones((n,n))
for i in range(1,n):
    b=np.ones((n,n))
    b[i:-i,i:-i] = 0
    A=b+A
A

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.],
       [10.,  9.,  8.,  8.,  8.,  8.,  8.,  8.,  9., 10.],
       [10.,  9.,  8.,  7.,  7.,  7.,  7.,  8.,  9., 10.],
       [10.,  9.,  8.,  7.,  6.,  6.,  7.,  8.,  9., 10.],
       [10.,  9.,  8.,  7.,  6.,  6.,  7.,  8.,  9., 10.],
       [10.,  9.,  8.,  7.,  7.,  7.,  7.,  8.,  9., 10.],
       [10.,  9.,  8.,  8.,  8.,  8.,  8.,  8.,  9., 10.],
       [10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

### Сербаев Вадим СКБ172

Оценка: 0.25

Комментарий: For=1, While=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [81]:
import numpy as np

MaxNum = int(input())

M = np.zeros((MaxNum, MaxNum))
reg = 0
i=0
k=0
while i<MaxNum/2:
    while k<MaxNum-reg:
        M[reg][k]+=MaxNum-reg
        M[k][reg]+=MaxNum-reg
        M[k][MaxNum-reg-1]+=MaxNum-reg
        M[MaxNum-reg-1][k]+=MaxNum-reg
        k+=1
    i+=1
    reg+=1
    k=reg
    
for i in range(MaxNum):
    M[i][i]=M[i][i]/2
    M[MaxNum-i-1][i] = M[MaxNum-i-1][i]/2
    
    
print(M)




18
[[18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]
 [18. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 18.]
 [18. 17. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 17. 18.]
 [18. 17. 16. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 11. 10. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 11. 10. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17. 18.]
 [18. 17. 16. 15. 14. 

### Булгаков Виталий СКБ172

Оценка: 0.25

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [53]:
import numpy as np
a = int(input()) #больше 13 вывод получится не красивый
pyr = np.ones((a, a)) * a
if a % 2:
    pyr[a // 2 , a // 2] -= a // 2
for i in range(a // 2):
    pyr[i, i : a - i] -= i
    pyr[-i - 1, i : a - i] -= i
    pyr[i + 1 : a - i - 1, i] -= i
    pyr[i + 1 : a - i - 1, - i - 1] -= i
pyr
    

13


array([[13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [13., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 13.],
       [13., 12., 11., 11., 11., 11., 11., 11., 11., 11., 11., 12., 13.],
       [13., 12., 11., 10., 10., 10., 10., 10., 10., 10., 11., 12., 13.],
       [13., 12., 11., 10.,  9.,  9.,  9.,  9.,  9., 10., 11., 12., 13.],
       [13., 12., 11., 10.,  9.,  8.,  8.,  8.,  9., 10., 11., 12., 13.],
       [13., 12., 11., 10.,  9.,  8.,  7.,  8.,  9., 10., 11., 12., 13.],
       [13., 12., 11., 10.,  9.,  8.,  8.,  8.,  9., 10., 11., 12., 13.],
       [13., 12., 11., 10.,  9.,  9.,  9.,  9.,  9., 10., 11., 12., 13.],
       [13., 12., 11., 10., 10., 10., 10., 10., 10., 10., 11., 12., 13.],
       [13., 12., 11., 11., 11., 11., 11., 11., 11., 11., 11., 12., 13.],
       [13., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 13.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13.]])

### Андреева Влада СКБ171

Оценка: 0.75

Комментарий: Recursion=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [35]:
import numpy as np

n = int(input())
A = np.ones((n,n))*n

def base(A, k):
    b = np.ones((n,n))
    b[:,0:k] = 0
    b[:,-k:] = 0
    b[0:k,:] = 0
    b[-k:,:] = 0
    A -= b
    k += 1
    if k <= n // 2:
        base(A, k)
    else:
        print(A)
    
base(A, 1)

7
[[7. 7. 7. 7. 7. 7. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 5. 4. 5. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


### Клопов Владислав СКБ172

Оценка: 0.75

Комментарий: While=1

In [2]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [23]:
import numpy as np
n=int(input())
s = n
size = np.array([0,n])
matrix = np.zeros((n, n))
while size[1] >= size[0]:
    matrix[size[0]:size[1],size[0]:size[1]]=np.zeros((s, s))+n
    n-=1
    s-=2
    size+=[1,-1]
matrix

8


array([[8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 7., 7., 7., 7., 7., 7., 8.],
       [8., 7., 6., 6., 6., 6., 7., 8.],
       [8., 7., 6., 5., 5., 6., 7., 8.],
       [8., 7., 6., 5., 5., 6., 7., 8.],
       [8., 7., 6., 6., 6., 6., 7., 8.],
       [8., 7., 7., 7., 7., 7., 7., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.]])

### Сарахан Владислав СКБ172

Оценка: 0.75

Комментарий: For=1

In [135]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [136]:
import numpy as np
n = int(input())
start = (n // 2) +1
startArray = []
if n % 2 == 0:
    startArray = np.array([[start, start], [start, start]])
else:
    startArray = np.array([[start]])
for i in range(start + 1, n+1):
    startArray = np.pad(startArray, pad_width=[(1,1),(1,1)], mode='constant', constant_values=i)
print(startArray)

7
[[7 7 7 7 7 7 7]
 [7 6 6 6 6 6 7]
 [7 6 5 5 5 6 7]
 [7 6 5 4 5 6 7]
 [7 6 5 5 5 6 7]
 [7 6 6 6 6 6 7]
 [7 7 7 7 7 7 7]]


### Старостин Данила СКБ172

Оценка: 0

Комментарий: No solution.

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


### Стрекнев Денис СКБ172

Оценка: 0.5

Комментарий: For=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [120]:
import numpy as np
n=int(input())
m=np.zeros((n,n), dtype=int)
m1=np.zeros((n,n), dtype=int)
for i in range(n):
    for k in range(i,n-i):
        m[i][k]=n-i
        m1[i][k]=n-i
m2=np.flipud(m1)
m3=m.transpose()
di=np.diag_indices(n)
m3[di]=0
m3[::-1][di]=0
m4=np.fliplr(m3)
m5=m1+m2+m3+m4
if n%2==1:
    m5[n//2][n//2]=m5[n//2][n//2]/2
m5 
#для четного n работает также корректно

7


array([[7, 7, 7, 7, 7, 7, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 5, 4, 5, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 7, 7, 7, 7, 7, 7]])

### Дородный Дмитрий СКБ172

Оценка: 0.25

Комментарий: For=2, Map=1

In [323]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [73]:
import numpy as np
n = int(input())

if n==1: print('[[1]]')
else:
    iter_layer = [i for i in range(1,n+1)]
    init_layer = [np.ones(n)*n for i in range(n)]

    x = list(map(lambda x,y: np.hstack((np.hstack((iter_layer[::-1][:y],x[y:-y]-y)), iter_layer[::-1][:y][::-1])), init_layer, iter_layer))
    x.insert(0, np.ones(n)*n)

    print(np.vstack(((x[:(n+1)//2],x[:n//2][::-1]))))

 7


[[7. 7. 7. 7. 7. 7. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 5. 4. 5. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


### Шемякин Дмитрий СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],  
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [33]:
import numpy as np

n = int(input())

board = np.zeros((n,n))
count = 0
for i in range(n,(n-((n+1)//2)),-1):
    board[count:n-count:,count:n-count:] = i 
    count += 1
print(board)


9
[[9. 9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 8. 8. 8. 8. 8. 8. 8. 9.]
 [9. 8. 7. 7. 7. 7. 7. 8. 9.]
 [9. 8. 7. 6. 6. 6. 7. 8. 9.]
 [9. 8. 7. 6. 5. 6. 7. 8. 9.]
 [9. 8. 7. 6. 6. 6. 7. 8. 9.]
 [9. 8. 7. 7. 7. 7. 7. 8. 9.]
 [9. 8. 8. 8. 8. 8. 8. 8. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9.]]


### Никитина Елизавета СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [15]:
import numpy as np


n = int(input())
A = np.ones((n, n), dtype=int)
for i in range(n):
    A[i:n - i,i:n - i] = n - i
print('для n = {}, A=\n{}'.format(n, A))

5
для n = 5, A=
[[5 5 5 5 5]
 [5 4 4 4 5]
 [5 4 3 4 5]
 [5 4 4 4 5]
 [5 5 5 5 5]]


### Семенов Игорь СКБ172

Оценка: 0.5

Комментарий: For=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [8]:
import numpy as np
np.set_printoptions(precision=3)
n=5
def f(n):
    arr=np.ones((n,n))

    for i in range(n):
        for j in range(n):
            arr[i,j]=n-min(n-1-i,n-1-j,i,j)
    return arr
print(f(10))

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


### Шамрин Игорь СКБ172

Оценка: 0.25

Комментарий: For=3

In [134]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]

[7, 7, 7, 7, 7, 7, 7]

In [185]:
import numpy as np
n = 7
a =  np.array([n for i in range(0,n)]).reshape(-1,1)
A = a
for i in range(1,n):
    A = np.hstack((A,a))
for i in range(0,n):
    A[i,i:n-i] = n-i
    A[n-i-1,i:n-i] = n-i
    A[i:n-i,i] = n-i
    A[i:n-i, n-i-1] = n-i
A

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 5, 4, 5, 6, 7],
       [7, 6, 5, 5, 5, 6, 7],
       [7, 6, 6, 6, 6, 6, 7],
       [7, 7, 7, 7, 7, 7, 7]])

### Щербаков Игорь СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [292]:
import numpy as np
def build_pyramid(k):
    A = np.full((k,k),k)
    for i in range(k-2, 0, -2):
        B=np.ones((i, i))
        B=np.pad(B,pad_width=(k-i)//2,mode='constant', constant_values=0)
        A=A-B
    A=A.astype(int) 
    return A
print(build_pyramid(7))        

[[7 7 7 7 7 7 7]
 [7 6 6 6 6 6 7]
 [7 6 5 5 5 6 7]
 [7 6 5 4 5 6 7]
 [7 6 5 5 5 6 7]
 [7 6 6 6 6 6 7]
 [7 7 7 7 7 7 7]]


### Шомахов Идар СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [77]:
import numpy as np

n = int(input())
a = np.ones((n, n), dtype = int)
for i in range(n):
    a[i:n - i,i:n - i] = n - i

4


array([[4, 4, 4, 4],
       [4, 3, 3, 4],
       [4, 3, 3, 4],
       [4, 4, 4, 4]])

### Григорьев Илья СКБ171

Оценка: 0.75

Комментарий: For=1

In [31]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [32]:
import numpy as np
import math

n = int(input())
A = np.ones((n,n), dtype = int)*n

for i in range(1,math.ceil(n / 2)):
    B = np.ones((n,n), dtype = int)#вычитаем единичную матрицу из внутренней части матрицы, каждый раз уменьшая её размер на 1
    B[0:i] = 0
    B[-i:n] = 0
    B[:,0:i] = 0
    B[:,-i:n] = 0
    A = A - B    
        
print(A)

5
[[5 5 5 5 5]
 [5 4 4 4 5]
 [5 4 3 4 5]
 [5 4 4 4 5]
 [5 5 5 5 5]]


### Фомин Илья СКБ171

Оценка: 0.75

Комментарий: For=1

In [28]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [29]:
import numpy as np

n = int(input())
x = np.ones((n, n))
for i in range(n):
    x[i:n - i,i:n - i] = n - i
print(x)

17
[[17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]
 [17. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 17.]
 [17. 16. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 16. 17.]
 [17. 16. 15. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10. 10. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10. 10. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 15. 16. 17.]
 [1

### Синицын Константин СКБ172

Оценка: 0.25

Комментарий: For=3

In [1]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [108]:
import numpy as np

n = int(input())
k = n // 2 + n % 2
matrix = np.ones((k, k), int) * n

for i in range(1, k+1):
    A = np.array([0] * k)
    B = np.array([0]*i + [1]*(k-i))
    C = A
    
    for j in range(i-1):
        C = np.vstack((C, A))
    for j in range(k-i):
        C = np.vstack((C, B))

    matrix = matrix - C

if n % 2 != 0:
    print(np.hstack((np.vstack((matrix[:-1:], np.flipud(matrix))), np.fliplr(np.vstack((matrix[:-1:], np.flipud(matrix))))[::, 1::])))
else:
    print(np.hstack((np.vstack((matrix, np.flipud(matrix))), np.fliplr(np.vstack((matrix, np.flipud(matrix)))))))

9
[[9 9 9 9 9 9 9 9 9]
 [9 8 8 8 8 8 8 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 6 5 6 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 8 8 8 8 8 8 9]
 [9 9 9 9 9 9 9 9 9]]


### Смирнов Константин СКБ172

Оценка: 0.25

Комментарий: For=3

In [33]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]

In [34]:
import numpy as np

n = 8
arr = np.empty((n, n))
    
for i in range(n//2 + 1):
    for j in range(i, n-i):
        for k in range(i, n-i):
            arr[i, j] = arr[j, i] = arr[-i-1, -j-1] = arr[-j-1, -i-1] = n - i

print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]


### Расторгуева Мария СКБ171

Оценка: 1

Комментарий: -

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [122]:
import numpy as np
n = int(input())
def func (i, j):
    return int(max (i+1, j+1, n-i, n-j))
A = np.fromfunction(np.vectorize(func), (n, n))
print (A)

7
[[7 7 7 7 7 7 7]
 [7 6 6 6 6 6 7]
 [7 6 5 5 5 6 7]
 [7 6 5 4 5 6 7]
 [7 6 5 5 5 6 7]
 [7 6 6 6 6 6 7]
 [7 7 7 7 7 7 7]]


### Гвасалия Метью СКБ172

Оценка: 0

Комментарий: For=1, Map=2, Reduce=4

In [9]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [24]:
import numpy as np

from functools import reduce

myvstack = lambda x,y: np.vstack((x,y))
n = int(input())
cast = lambda xs: list(map(lambda y: 0 if (y < (n - len(xs))//2 or y > (n-1-(n - len(xs))//2)) else xs[0],range(n)))    
broadc = [cast(np.ones(n-2*i)) for i in range(1,-(-n//2))]
inmat = np.ones(n)*n
broadc.insert(0,inmat)
parts = list(map(lambda ind: reduce(lambda x,y: x - y,broadc[:ind+1]),range(0,-(-n//2))))
stacked = reduce(myvstack,parts)
if n % 2 == 0:
    print(myvstack(stacked,reduce(myvstack,reversed(parts))))
else:
    print(myvstack(stacked,reduce(myvstack,reversed(parts[:-1]))))

10
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


### Поддубный Михаил СКБ172

Оценка: 0.75

Комментарий: For=1

In [31]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [32]:
import numpy as np
k = int(input())
matr = np.ones((k,k),dtype=np.int32)*k

for i in range(1, k // 2):
    matr[i,i:k-i] -= i
    matr[-i-1,i:k-i] -= i
    matr[i+1:k-i-1,i] -= i
    matr[i+1:k-i-1,-i-1] -= i
if k % 2:
    matr[k//2,k//2]-=k//2
print(matr)

9
[[9 9 9 9 9 9 9 9 9]
 [9 8 8 8 8 8 8 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 6 5 6 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 8 8 8 8 8 8 9]
 [9 9 9 9 9 9 9 9 9]]


### Миронов Никита СКБ171

Оценка: 0

Комментарий: No solution.

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


### Шубин Никита СКБ172

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [119]:
import numpy as np
def getpyr(n):
    pyr = np.ones((n,n))
    pyr *= n
    for i in range(n//2 if  n%2 == 0 else n//2+1):
        pyr[i:-i, i:-i] -= 1
    return pyr
print(getpyr(8))

[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]


### Щеглова Полина СКБ172

Оценка: 0.75

Комментарий: Map=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [139]:
import numpy as np
n = 17
arr = np.zeros(n*n).reshape(n, n)

def fill_layer(num, value):
    arr[num][num:n-num]=[value]*(n-2*num)
    arr[num:n-num, num]=[value]*(n-2*num)
    arr[num:n-num,n-num-1]=[value]*(n-2*num)
    arr[n-num-1][num:n-num]=[value]*(n-2*num)
values = np.flip(np.arange(n-(n//2+n%2+1), n+1))
list(map(fill_layer,np.arange(n//2+n%2), values))
print(arr)

[[17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17.]
 [17. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 16. 17.]
 [17. 16. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 16. 17.]
 [17. 16. 15. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10. 10. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 10. 10. 10. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 11. 11. 11. 11. 11. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 12. 12. 12. 12. 12. 12. 12. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 13. 13. 13. 13. 13. 13. 13. 13. 13. 14. 15. 16. 17.]
 [17. 16. 15. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 15. 16. 17.]
 [17. 

### Мухамадиева Регина СКБ172

Оценка: 0.5

Комментарий: For=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [15]:
import numpy as np
n=int(input())
m=np.zeros((n,n))
for i in range((n+1)//2):
    for j in range(i,n-i):
        m[i,j]=n-i
        m[j,i]=n-i
        m[n-1-i,j]=n-i
        m[j,n-1-i]=n-i
print(m)

7
[[7. 7. 7. 7. 7. 7. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 5. 4. 5. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


### Астраханцев Роман СКБ171

Оценка: 0.5

Комментарий: For=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [96]:
import numpy as np
n=int(input())
arr = np.zeros((n,n))
for j in range(n, n//2, -1):
    for i in range(4):
        arr[n-j, n-j:j-n-1] = np.full(shape=n-1-2*(n-j) if n-1-2*(n-j)!=0 else 1, fill_value=j)
        arr = np.rot90(arr, 1)
print(arr)

8
[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 5. 5. 6. 7. 8.]
 [8. 7. 6. 6. 6. 6. 7. 8.]
 [8. 7. 7. 7. 7. 7. 7. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]


### Бесчастных Роман СКБ171

Оценка: 0.75

Комментарий: For=1

In [5]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [8]:
import numpy as numpy

dim = int(input())
firstNum = (dim // 2) +1
matrix = []
if dim % 2 == 0:
    matrix = numpy.array([[firstNum, firstNum], [firstNum, firstNum]])
else:
    matrix = numpy.array([[firstNum]])
for i in range(firstNum + 1, dim+1):
    matrix = numpy.pad(matrix, pad_width=[(1, 1), (1, 1)], constant_values=i)
print(matrix)

5
[[5 5 5 5 5]
 [5 4 4 4 5]
 [5 4 3 4 5]
 [5 4 4 4 5]
 [5 5 5 5 5]]


In [9]:
import numpy as numpy

dim = int(input())
firstNum = (dim // 2) +1
matrix = []
if dim % 2 == 0:
    matrix = numpy.array([[firstNum, firstNum], [firstNum, firstNum]])
else:
    matrix = numpy.array([[firstNum]])
for i in range(firstNum + 1, dim+1):
    matrix = numpy.pad(matrix, pad_width=[(1, 1), (1, 1)], constant_values=i)
print(matrix)

8
[[8 8 8 8 8 8 8 8]
 [8 7 7 7 7 7 7 8]
 [8 7 6 6 6 6 7 8]
 [8 7 6 5 5 6 7 8]
 [8 7 6 5 5 6 7 8]
 [8 7 6 6 6 6 7 8]
 [8 7 7 7 7 7 7 8]
 [8 8 8 8 8 8 8 8]]


### Музаффаров Руфат СКБ171

Оценка: 0

Комментарий: No solution.

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


### Гаварина Светлана СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [245]:
import numpy as np

def create_pyr(n):
    pyr = np.tile(n, (n,n))
    for i in range(n):
        pyr[i:-i,i:-i] -= 1
    return pyr

n = 15
print(create_pyr(n))

[[15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
 [15 14 14 14 14 14 14 14 14 14 14 14 14 14 15]
 [15 14 13 13 13 13 13 13 13 13 13 13 13 14 15]
 [15 14 13 12 12 12 12 12 12 12 12 12 13 14 15]
 [15 14 13 12 11 11 11 11 11 11 11 12 13 14 15]
 [15 14 13 12 11 10 10 10 10 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  9  9 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  8  9 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  9  9 10 11 12 13 14 15]
 [15 14 13 12 11 10 10 10 10 10 11 12 13 14 15]
 [15 14 13 12 11 11 11 11 11 11 11 12 13 14 15]
 [15 14 13 12 12 12 12 12 12 12 12 12 13 14 15]
 [15 14 13 13 13 13 13 13 13 13 13 13 13 14 15]
 [15 14 14 14 14 14 14 14 14 14 14 14 14 14 15]
 [15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]]


### Дундуков Семен СКБ171

Оценка: 0.75

Комментарий: For=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [ ]:
import numpy as np

n = int(input())
a = np.empty((n,n))
if n%2 == 0: m = n//2
else: m = n//2+1
for i in range(m):
    a[i:n-i,i:n-i] = n-i
print(a)

### Бень Таисия СКБ171

Оценка: 0.5

Комментарий: For=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [4]:
import numpy as np
k = int(input())
matrix = np.zeros((k,k))
for i in range (k, k//2, -1):
    for j in range(4):
        matrix[k-i, k-i:i-k-1] = np.full(shape=k-1-2*(k-i) if k-1-2*(k-i) != 0 else 1, fill_value = i)
        matrix = np.rot90(matrix, 1)
print(matrix)


10
[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  6.  6.  7.  8.  9. 10.]
 [10.  9.  8.  7.  7.  7.  7.  8.  9. 10.]
 [10.  9.  8.  8.  8.  8.  8.  8.  9. 10.]
 [10.  9.  9.  9.  9.  9.  9.  9.  9. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


### Козликина Татьяна СКБ172

Оценка: 0.25

Комментарий: For=3

In [34]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [35]:
import numpy as np

def NewMatrix(n):
    matrix = np.full((n,n), n) #Создаем матрицу n*n и заполняем всю числами n
    for i in range (1, n): #Задаём приближение к центру матрицы
        for k in range(i, n - i):
            for l in range(i, n - i):
                matrix[k,l] = n - i
    return matrix

print("Введите размер матрицы: ")
n = int(input())
print(NewMatrix(n))

Введите размер матрицы: 
15
[[15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
 [15 14 14 14 14 14 14 14 14 14 14 14 14 14 15]
 [15 14 13 13 13 13 13 13 13 13 13 13 13 14 15]
 [15 14 13 12 12 12 12 12 12 12 12 12 13 14 15]
 [15 14 13 12 11 11 11 11 11 11 11 12 13 14 15]
 [15 14 13 12 11 10 10 10 10 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  9  9 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  8  9 10 11 12 13 14 15]
 [15 14 13 12 11 10  9  9  9 10 11 12 13 14 15]
 [15 14 13 12 11 10 10 10 10 10 11 12 13 14 15]
 [15 14 13 12 11 11 11 11 11 11 11 12 13 14 15]
 [15 14 13 12 12 12 12 12 12 12 12 12 13 14 15]
 [15 14 13 13 13 13 13 13 13 13 13 13 13 14 15]
 [15 14 14 14 14 14 14 14 14 14 14 14 14 14 15]
 [15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]]


### Апресян Тигран СКБ171

Оценка: 0.75

Комментарий: Recursion=1

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [139]:
import numpy as np
n = 7
c = np.ones((n,n))*n
def fic(f,x):
    c1 = np.ones((n,n))
    c1[0:x,] = 0
    c1[-x:,] = 0
    c1[:,0:x] = 0
    c1[:,-x:] = 0
    x+=1
    f = f - c1
    return fic(f,x) if x<=n//2+1 else print(f)
fic(c,1)

[[7. 7. 7. 7. 7. 7. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 5. 4. 5. 6. 7.]
 [7. 6. 5. 5. 5. 6. 7.]
 [7. 6. 6. 6. 6. 6. 7.]
 [7. 7. 7. 7. 7. 7. 7.]]


### Долотов Фёдор СКБ172

Оценка: 0.25

Комментарий: For=1, While=2

In [ ]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [9]:
import numpy as np

a = int(input())
M = np.zeros((a, a))
b, k, i = 0, 0, 0

while i < a/2:
    while k < a - b:
        M[b][k] += a - b
        M[k][b] += a - b
        M[k][a - b - 1] += a - b
        M[a - b - 1][k] += a - b
        k += 1
    b += 1
    k = b
    i += 1
    
for i in range(a):
    M[i][i] = M[i][i]/2
    M[a - i - 1][i] = M[a - i - 1][i]/2
    
    
print(M)

80
[[80. 80. 80. ... 80. 80. 80.]
 [80. 79. 79. ... 79. 79. 80.]
 [80. 79. 78. ... 78. 79. 80.]
 ...
 [80. 79. 78. ... 78. 79. 80.]
 [80. 79. 79. ... 79. 79. 80.]
 [80. 80. 80. ... 80. 80. 80.]]


### Попов Юрий СКБ172

Оценка: 0.25

Комментарий: For=3

In [29]:
# при помощи NumPy для заданного n сгенерировать матрицу A размера n x n
# по правилу пирамиды, в основании которой элементы равны n, а при приближении
# к вершине - уменьшаются:

# для n = 4, A = 
#[[4, 4, 4, 4],
# [4, 3, 3, 4],
# [4, 3, 3, 4],
# [4, 4, 4, 4]]

# для n = 7, A = 
# [[7, 7, 7, 7, 7, 7, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 5, 4, 5, 6, 7],
#  [7, 6, 5, 5, 5, 6, 7],
#  [7, 6, 6, 6, 6, 6, 7],
#  [7, 7, 7, 7, 7, 7, 7]]


In [30]:
# Задание_14
import numpy as np

print('Укажите параметр n для матрицы: ')
n = int(input())


def generateMatrix(N):
    if N <= 0:
        print('please pick N as a positive integer value')
        return -1

    A = np.full((N,N), N)
    for i in range (1, N, 1):
        for k in range(i, N - i):
            for l in range(i, N - i):
                A[k,l] = N - i

    print(A)


generateMatrix(n)

Укажите параметр n для матрицы: 
9
[[9 9 9 9 9 9 9 9 9]
 [9 8 8 8 8 8 8 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 6 5 6 7 8 9]
 [9 8 7 6 6 6 7 8 9]
 [9 8 7 7 7 7 7 8 9]
 [9 8 8 8 8 8 8 8 9]
 [9 9 9 9 9 9 9 9 9]]
